import os
from pathlib import Path
import random
import json
import csv
import shutil
from faker import Faker
from reportlab.pdfgen import canvas
from openpyxl import Workbook

from apps.const import (
    OBJECTS_CONTENTVERSION_DIR,
    OBJECTS_CONTENTVERSIONDATA_DIR,
    OBJECTS_CONTENTDOCUMENTLINK_DIR,
    OBJECTS_DOWNLOAD_MASTER_DIR,
    OBJECTS_DOWNLOAD_MASTERWORK_DIR,
    STORAGE_FILE_ROOT,
    QUEUE_ROOT,
    QUEUE_ACCEPTED_DIR,
    QUEUE_COMPLETED_DIR,
    QUEUE_CREATE_DIR,
    QUEUE_ERROR_DIR,
    QUEUE_PROCESSING_DIR
)

fake = Faker("ja_JP")

EXTS = ["txt", "csv", "pdf", "json", "xlsx"]

BASE = Path(os.path.dirname(__file__)).resolve()

# ------------------------------------------------------------
# フォルダクリア（安全に削除 → 再作成）
# ------------------------------------------------------------
def clear_dir(path: Path):
    if path.exists():
        shutil.rmtree(path)
    path.mkdir(parents=True, exist_ok=True)


clear_dir(OBJECTS_CONTENTVERSION_DIR)
clear_dir(OBJECTS_CONTENTVERSIONDATA_DIR)
clear_dir(OBJECTS_CONTENTDOCUMENTLINK_DIR)
clear_dir(OBJECTS_DOWNLOAD_MASTER_DIR)
clear_dir(OBJECTS_DOWNLOAD_MASTERWORK_DIR)
clear_dir(STORAGE_FILE_ROOT)
clear_dir(QUEUE_ROOT)
clear_dir(QUEUE_ACCEPTED_DIR)
clear_dir(QUEUE_COMPLETED_DIR)
clear_dir(QUEUE_CREATE_DIR)
clear_dir(QUEUE_ERROR_DIR)
clear_dir(QUEUE_PROCESSING_DIR)

# ------------------------------------------------------------
# 各ファイル生成関数
# ------------------------------------------------------------
def create_txt(path: Path):
    text = "\n".join(fake.sentences(nb=5))
    path.write_text(text, encoding="utf-8")

def create_csv(path: Path):
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(["id", "name", "email"])
        for _ in range(10):
            writer.writerow([fake.uuid4(), fake.name(), fake.email()])


def create_pdf(path: Path):
    c = canvas.Canvas(str(path))
    c.drawString(100, 800, "Sample PDF generated by Faker")
    for i in range(10):
        c.drawString(100, 780 - i * 20, fake.sentence())
    c.save()

def create_json(path: Path):
    data = {
        "id": fake.uuid4(),
        "name": fake.name(),
        "email": fake.email(),
        "address": fake.address(),
    }
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")


def create_xlsx(path: Path):
    wb = Workbook()
    ws = wb.active
    if ws:
        ws.append(["id", "name", "email"])
        for _ in range(10):
            ws.append([str(fake.uuid4()), fake.name(), fake.email()])
    wb.save(path)

GENERATORS = {
    "txt": create_txt,
    "csv": create_csv,
    "pdf": create_pdf,
    "json": create_json,
    "xlsx": create_xlsx,
}

# ------------------------------------------------------------
# メインループ：ファイル生成 + DownloadMaster__c JSON 生成
# ------------------------------------------------------------
for i in range(1, 12):
    ext = random.choice(EXTS)
    real_file_path = STORAGE_FILE_ROOT / f"file_{i}.{ext}"

    # 本物のファイルを生成
    GENERATORS[ext](real_file_path)

print("セットアップ完了！")
print(f"{STORAGE_FILE_ROOT}にファイルを作成しました")
